version: '3.8'
services:
  front:
    extends:
      file: frontend/docker-compose.yaml
      service: app
  gateway:
    extends:
      file: backend/GatewayService/docker-compose.yaml
      service: app
  notification:
    extends:
      file: backend/NotificationService/docker-compose.yaml
      service: app
  order:
    extends:
      file: backend/OrderService/docker-compose.yaml
      service: app