version: '3.8'
services:
  front:
    extends:
      file: frontend/docker-compose.yaml
      service: app
  main:
    extends:
      file: backend/MainService/docker-compose.yaml
      service: app
  notification:
    extends:
      file: backend/NotificationService/docker-compose.yaml
      service: app